#!/usr/bin/env python3
"""
30-Day Content Calendar
@888abundancefrequency + @liquidinsights
Generated by NOVA
"""
import random
from datetime import datetime, timedelta

# Content themes for 30 days
ABUNDANCE_THEMES = [
    "888 abundance portal",
    "manifestation energy",
    "wealth consciousness",
    "numerology signals",
    "spiritual finance",
    "money mindset",
    "abundance blocks",
    "financial liberation",
    "flow state",
    "trust the process",
    "energy alignment",
    "wealth frequency",
    "sacred money",
    "prosperity mindset",
    "abundance mindset",
    "financial freedom",
    "wealth journey",
    "money energy",
    "abundance vibration",
    "spiritual wealth",
    "prosperity consciousness",
    "wealth creation",
    "abundance rituals",
    "money psychology",
    "wealth attraction",
    "financial sovereignty",
    "abundance grace",
    "prosperity flow",
    "wealth alignment",
    "abundance awakening",
]

MARKET_THEMES = [
    "crypto market analysis",
    "defi education",
    "solana ecosystem",
    "tokenomics 101",
    "market sentiment",
    "whale movements",
    "liquidity pools",
    "yield farming",
    "nft market",
    "web3 trends",
    "defi strategies",
    "crypto psychology",
    "market cycles",
    "bitcoin analysis",
    "solana fundamentals",
    "defi basics",
    "token utility",
    "market education",
    "crypto signals",
    "investment basics",
    "risk management",
    "portfolio strategy",
    "trading psychology",
    "market trends",
    "defi protocols",
    "crypto education",
    "blockchain basics",
    "web3 education",
    "defi opportunities",
    "crypto fundamentals",
]

CALL_TO_ACTIONS = [
    "Save this for later ✨",
    "Share with someone who needs this 💫",
    "Tag someone in the comments 👇",
    "Turn this into your lockscreen 🖤",
    "DM me your goals 👑",
    "Save this 💜",
    "Share the abundance ✨",
    "Comment YOUR goal 👇",
    "Save, share, repeat 💫",
    "Send this to a friend 💕",
]

ABUNDANCE_REMINDERS = [
    "Your frequency attracts your reality.",
    "Wealth is a state of mind.",
    "The universe rewards those who act.",
    "Abundance is your birthright.",
    "Flow more, fear less.",
    "You are the wealth.",
    "Money is energy.",
    "Your mind is your bank.",
    "Abundance flows to those who receive.",
    "The secret is in the belief.",
]

def generate_day_content(day: int, date: datetime) -> dict:
    """Generate content for a specific day"""
    
    # Alternate between accounts
    if day % 2 == 1:
        # @888abundancefrequency
        theme = ABUNDANCE_THEMES[day % len(ABUNDANCE_THEMES)]
        return {
            "day": day,
            "date": date.strftime("%B %d, %Y"),
            "account": "@888abundancefrequency",
            "theme": theme,
            "content": generate_abundance_post(theme),
            "hashtags": generate_abundance_hashtags(),
        }
    else:
        # @liquidinsights
        theme = MARKET_THEMES[day % len(MARKET_THEMES)]
        return {
            "day": day,
            "date": date.strftime("%B %d, %Y"),
            "account": "@liquidinsights",
            "theme": theme,
            "content": generate_market_post(theme),
            "hashtags": generate_market_hashtags(),
        }

def generate_abundance_post(theme: str) -> str:
    templates = [
        f"The 888 frequency is amplifying.\n\nYou're not behind. You're exactly where you need to be.\n\n{random.choice(ABUNDANCE_REMINDERS)}\n\n{random.choice(CALL_TO_ACTIONS)}",
        f"888 isn't just a number.\n\nIt's a frequency.\n\nA signal.\n\nA reminder that the universe is conspiring in your favor.\n\n{random.choice(ABUNDANCE_REMINDERS)}\n\n{random.choice(CALL_TO_ACTIONS)}",
        f"What if the money you seek...\nis already on its way?\n\nThe 888 portal is open.\n\n{random.choice(ABUNDANCE_REMINDERS)}\n\n{random.choice(CALL_TO_ACTIONS)}",
        f"Most people wait for abundance.\n\nOthers become the frequency.\n\n888 is calling.\n\n{random.choice(ABUNDANCE_REMINDERS)}\n\n{random.choice(CALL_TO_ACTIONS)}",
    ]
    return random.choice(templates)

def generate_market_post(theme: str) -> str:
    templates = [
        f"Quick {theme} breakdown:\n\nHere's what you need to know:\n\n1. The market is shifting\n2. {random.choice(['Smart money is positioning.', 'Whales are accumulating.', 'The narrative is changing.'])}\n3. What to watch:\n\n{random.choice(['Save this for later', 'Bookmark this', 'Save and share'])}\n\n#crypto #{theme.replace(' ','')} #investing #web3",
        f"{theme.upper()} 101\n\nMost people don't understand this. Here's the truth:\n\n{random.choice(['The opportunity is in the chaos.', 'The dip is a gift.', 'Smart investors are buying.'])}\n\nBookmark this. You'll need it.\n\n#crypto #education #{theme.replace(' ','')} #defi",
    ]
    return random.choice(templates)

def generate_abundance_hashtags() -> str:
    tags = [
        "#888", "#abundance", "#manifestation", "#spiritualwealth",
        "#moneymindset", "#numerology", "#lawofattraction",
        "#wealthconsciousness", "#frequency", "#universe",
        "#abundancemindset", "#financialfreedom", "#spiritual",
    ]
    return " ".join(random.sample(tags, 8))

def generate_market_hashtags() -> str:
    tags = [
        "#crypto", "#bitcoin", "#solana", "#defi",
        "#web3", "#trading", "#investing", "#blockchain",
        "#cryptocurrency", "#trading", "#market", "#analysis",
    ]
    return " ".join(random.sample(tags, 8))

def generate_30_days():
    """Generate 30 days of content"""
    start_date = datetime(2026, 3, 2)
    calendar = []
    
    for day in range(1, 31):
        date = start_date + timedelta(days=day - 1)
        calendar.append(generate_day_content(day, date))
    
    return calendar

if __name__ == "__main__":
    print("=" * 60)
    print("30-DAY CONTENT CALENDAR")
    print("@888abundancefrequency + @liquidinsights")
    print("=" * 60)
    
    calendar = generate_30_days()
    
    for post in calendar:
        print(f"\n--- DAY {post['day']} | {post['date']} | {post['account']} ---")
        print(f"Theme: {post['theme']}")
        print(f"\n{post['content']}")
        print(f"\n{post['hashtags']}")
        print("-" * 40)
