#!/bin/bash
# Auto Code Review Script
# Reviews PRs with 3 AI models: Codex, Gemini, Claude
# LiQUiD SOUND | UAI

set -e

REPO="$1"
PR_NUMBER="$2"
GITHUB_TOKEN="$3"

if [ -z "$REPO" ] || [ -z "$PR_NUMBER" ]; then
    echo "Usage: ./code-review.sh <repo> <pr_number> [github_token]"
    exit 1
fi

GITHUB_TOKEN="${GITHUB_TOKEN:-$GITHUB_TOKEN}"

# Config
REVIEWERS=("codex" "gemini" "claude")
COLOR_CODEX="\033[0;34m"     # Blue
COLOR_GEMINI="\033[0;33m"   # Yellow
COLOR_CLAUDE="\033[0;36m"    # Cyan
COLOR_RESET="\033[0m"

echo "========================================"
echo "🔍 LiQUiD SOUND Auto Code Review"
echo "📝 PR #$PR_NUMBER"
echo "========================================"

# Get PR diff
PR_DIFF=$(gh pr diff "$PR_NUMBER" --repo "$REPO" 2>/dev/null || echo "")

if [ -z "$PR_DIFF" ]; then
    echo "❌ Could not fetch PR diff"
    exit 1
fi

# Extract changed files
CHANGED_FILES=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json changedFiles -q '.changedFiles' 2>/dev/null || echo "unknown")
echo "📁 Changed files: $CHANGED_FILES"

# === CODEX REVIEWER ===
echo -e "\n${COLOR_CODEX}🤖 Codex Reviewer (Edge Cases & Logic)${COLOR_RESET}"
CODEX_REVIEW=$(cat << 'EOF' | codex --model gpt-5.3-codex -c "model_reasoning_effort=high" -
Review this PR diff for:
1. Logic errors and edge cases
2. Missing error handling
3. Race conditions
4. Security vulnerabilities

Provide specific file:line comments. Mark issues as [CRITICAL], [WARNING], or [SUGGESTION].

EOF
)
echo "$CODEX_REVIEW"

# === GEMINI REVIEWER ===
echo -e "\n${COLOR_GEMINI}🔮 Gemini Reviewer (Security & Scalability)${COLOR_RESET}"
GEMINI_REVIEW=$(cat << 'EOF' | npx -y @google/gemini-code-assist@latest review --pr $PR_NUMBER --repo $REPO 2>/dev/null || echo "Gemini review unavailable"
EOF
)
# Fallback: basic security check
if [ -z "$GEMINI_REVIEW" ] || [ "$GEMINI_REVIEW" = "Gemini review unavailable" ]; then
    GEMINI_REVIEW=$(echo "$PR_DIFF" | grep -E "(password|secret|token|api_key|env\.|process\.env)" | head -5 | sed 's/^/⚠️ Potential secret leak: /')
fi
echo "$GEMINI_REVIEW"

# === CLAUDE REVIEWER ===
echo -e "\n${COLOR_CLAUDE}🧠 Claude Reviewer (Validation)${COLOR_RESET}"
CLAUDE_REVIEW=$(cat << 'EOF' | claude --model claude-opus-4.5 -p -
Review this PR for overall quality and architecture. Validate what other reviewers flagged.

Focus on:
1. Architecture decisions
2. Code quality
3. Test coverage
4. Performance implications

Mark as [APPROVED], [CHANGES_REQUESTED], or [CRITICAL_BLOCKER].

EOF
)
echo "$CLAUDE_REVIEW"

# === Summary ===
echo -e "\n========================================"
echo "📊 Review Summary"
echo "========================================"

# Post summary as PR comment
SUMMARY=$(cat << EOF
## 🔍 LiQUiD SOUND Auto Review

### 🤖 Codex (Logic & Edge Cases)
$(echo "$CODEX_REVIEW" | head -20)

### 🔮 Gemini (Security & Scale)
$(echo "$GEMINI_REVIEW" | head -10)

### 🧠 Claude (Architecture)
$(echo "$CLAUDE_REVIEW" | head -10)

---
*🤖 Auto-generated by LiQUiD SOUND UAI*
EOF
)

# Post comment
if [ -n "$GITHUB_TOKEN" ]; then
    gh pr comment "$PR_NUMBER" --repo "$REPO" --body "$SUMMARY" 2>/dev/null && echo "✅ Review posted to PR#$PR_NUMBER"
else
    echo "📝 Review (not posted - no token):"
    echo "$SUMMARY"
fi

echo "========================================"
echo "✅ Code review complete"
echo "========================================"
